default:
  listenAddr: ":6180"
  webSocketListenAddr: ""
  JWTSecret: ""
  expireTime: ""

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "chenteng"
  name: "kubemanage"
  maxOpenConns: 100
  maxLifetime: 20
  maxIdleConns: 10