default:
  listenAddr: ":6180"
  webSocketListenAddr: ""
  JWTSecret: "kubemanage"
  expireTime: 10

mysql:
  host: "192.168.2.101"
  port: "3307"
  user: "root"
  password: "Wk@18917902780"
  name: "kubemanage"
  maxOpenConns: 100
  maxLifetime: 20
  maxIdleConns: 10