KubeManage:
  PodLogTailLine: 2000
  ListenAddr: ":6180"
  WebSocketListenAddr: "0.0.0.0:6181"
  JWTSecret: "kubemanage"
  ExpireTime: 1
  Database:
    host: "yunxue521.top"
    port: "33026"
    user: "root"
    password: "1qaz@WSX"
    DBName: "kubemanage"
    MaxOpenConns: 100
    MaxLifetime: 20


